#
# Spring properties
#
spring.application.name=BookMyEvent
server.port=8080
server.servlet.context-path=/api/v1
password.reset.url=https://mclareni.github.io/evently_front/?renovationPassword&token={token}
front.url=https://mclareni.github.io/evently_front
#password.reset.url=https://sergiy5.github.io/evently_front/?renovationPassword&token={token}


#
# Mongodb properties cloud connect
#
spring.data.mongodb.uri=${MONGODB_URL}

#
# Mongodb properties local connect
#
#spring.data.mongodb.username=${DB_USER_NAME}
#spring.data.mongodb.password=${DB_PASSWORD}
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=eventDb
#spring.data.mongodb.authentication-database=admin

#
# Authentication properties
#
jwt.signing.key=${JWT_KEY}

#
# Mail service properties
#
cloud.server.url=${SERVER_URL}
#cloud.server.url=http://localhost:8080


server.swagger-ui.operationsSorter=method
server.swagger-ui.tagsSorter=alpha
server.swagger-ui.disable-swagger-default-url=false


#
# EMAIL HOST
#
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_ID}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.mime.charset=UTF-8
spring.mail.properties.mail.smtp.writetimeout= 10000
spring.mail.properties.mail.smtp.connectiontimeout= 10000
spring.mail.properties.mail.smtp.timeout= 10000
spring.mail.properties.mail.smtp.auth= true
spring.mail.properties.mail.smtp.starttls.enable= true
spring.mail.properties.mail.smtp.ssl.trust= smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required= true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

EMAIL_HOST= smtp.gmail.com
EMAIL_PORT= 587
