#
# Spring properties
#
spring.application.name=BookMyEvent
server.port=8080

#
# Mongodb properties cloud connect
#
spring.data.mongodb.uri=${MONGODB_URL}

#
# Mongodb properties local connect
#

#spring.data.mongodb.username=
#spring.data.mongodb.password=
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=eventDb
#spring.data.mongodb.authentication-database=admin