spring.application.name=BookMyEvent
server.port=8080

#spring.data.mongodb.authentication-database=Event-mongoDB
spring.data.mongodb.uri=mongodb+srv://jj3564527:MeSkUyCkG8o6dnSD@event-mongodb.pqwra.mongodb.net/eventDb?retryWrites=true&w=majority&appName=Event-mongoDB
#spring.data.mongodb.username=jj3564527
#spring.data.mongodb.password=MeSkUyCkG8o6dnSD
#spring.data.mongodb.uri=mongodb+srv://jj3564527:MeSkUyCkG8o6dnSD@cluster0.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
#spring.data.mongodb.database=eventDb
